import * as DialogPrimitive from "@radix-ui/react-dialog";
import { X } from "lucide-react";
import { cn } from "@/lib/utils";
const Dialog = DialogPrimitive.Root;
const DialogTrigger = DialogPrimitive.Trigger;
const DialogClose = DialogPrimitive.Close;
const DialogPortal = DialogPrimitive.Portal;
const DialogOverlay = ({ className, ...props }) => <DialogPrimitive.Overlay className={cn("fixed inset-0 z-50 bg-black/50", className)} {...props} />;
const DialogContent = ({ className, children, ...props }) => <DialogPortal><DialogOverlay/><DialogPrimitive.Content className={cn("fixed left-1/2 top-1/2 z-50 w-[calc(100%-2rem)] max-w-lg -translate-x-1/2 -translate-y-1/2 rounded-lg border bg-background p-6 shadow-lg", className)} {...props}>{children}<DialogPrimitive.Close className="absolute right-4 top-4"><X className="h-4 w-4"/></DialogPrimitive.Close></DialogPrimitive.Content></DialogPortal>;
const DialogHeader = ({ className, ...props }) => <div className={cn("flex flex-col gap-1.5", className)} {...props}/>;
const DialogFooter = ({ className, ...props }) => <div className={cn("flex justify-end gap-2", className)} {...props}/>;
const DialogTitle = DialogPrimitive.Title;
const DialogDescription = DialogPrimitive.Description;
export { Dialog, DialogTrigger, DialogClose, DialogContent, DialogHeader, DialogFooter, DialogTitle, DialogDescription };
